### ISSUE TITLE
Trim buttons let you go into a short position (if youre long and visa versa)

### ISSUE THREAD

**Issue by Dolivent** [pareeohnos/ktrade#14]
Trim buttons should be able to sell no more than the shares you own. Even if you submit a trim order, it hasn't been filled, and you click the button again (for whatever reason). A scenario where this is critical is if someone accidentally double clicks and submits sell orders in total in excess of what they have available to sell

**Comment by pareeohnos** [comment]
hmm damn I thought I'd protected against this already. Apparently I messed it up, but definitely need this!

**Comment by Dolivent** [comment]
Tested again:
1. I buy 14 shares
2.  I rapidly click Trim 1/2 x 2 times, I have 0 shares, but a stop of -7 shares remains
3.   I rapidly click Trim 1/2 x 3 times, then I end up with -14 shares
3.  I rapidly click Trim 1/2 x 4 times, then I end up with -21 shares.
