### ISSUE TITLE
LOD incorrect 

### ISSUE THREAD

**Issue by Dolivent** [pareeohnos/ktrade#21]
![image](https://user-images.githubusercontent.com/89076425/134361487-40995bfe-77cd-4939-898d-bb8bf5b6a2b3.png)

LOD also moves around when price hovers around the LOD price. Returns something along hte lines of "stop price and buy price are the same"

**Comment by pareeohnos** [comment]
ok I'm about 99% sure I've found the source of the problem, just need to find a nice and clean solution
