### ISSUE TITLE
Data not loading after adding ticker and refreshing

### ISSUE THREAD

**Issue by Dolivent** [pareeohnos/ktrade#22]
![image](https://user-images.githubusercontent.com/89076425/134361811-8ed883e5-e0ce-4a4b-9700-2cffdbdee4dc.png)

![image](https://user-images.githubusercontent.com/89076425/134361869-51203fc7-0d71-460b-8470-83a19895f0d6.png)

**Comment by Dolivent** [comment]
Data is also generally not loading. When i try the buy button i gert the following error:

`INFO:ibapi.client:REQUEST placeOrder {'orderId': 380, 'contract': 1652377263552: 0,AMZN,STK,,0.0,,,SMART,,USD,,,False,,combo:, 'order': 1652377983248: 380,0,0: STP SELL 3@179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.000000 }
INFO:ibapi.wrapper:ANSWER error {'reqId': 380, 'errorCode': 504, 'errorString': 'Not connected'}
ERROR:ibapi.wrapper:ERROR 380 504 Not connected`

**Comment by Dolivent** [comment]
After restarting the app, the data comes back and I'm able to place one trade. Then everything freezes again

**Comment by Dolivent** [comment]
Refresh for new data for newly added ticker also works after I restart the app, but only before i place a buy order

**Comment by pareeohnos** [comment]
Looks like something is disconnecting it from TWS and the app makes no attempt to reconnect. I think there's basically no error handling at the moment, so if it errors the background thread just dies and that's it. Will add more handling

**Comment by Dolivent** [comment]
Same issue for Trades page after submitting Sell orders

**Comment by Dolivent** [comment]
after adding the ticker to watchlist today, refresh didnt bring data up. Had to restart flask and yarn

**Comment by arashabedi67** [comment]
I have the same issue. @Dolivent were you able to fix?

**Comment by pareeohnos** [comment]
@Arash6771 have you got any logs that might help isolate the issue?
