### ISSUE TITLE
Trimming a position leaves the order with the incorrect status

### ISSUE THREAD

**Issue by pareeohnos** [pareeohnos/ktrade#30]
When we trim, the status of the trade switches to 'canceled' when it shouldn't. Ideally we should introduce one or more new statuses to cover these situations. Need to decide whether a trimmed order should still be shown as "complete" or do we mark it as "trimmed", or even "trimmed <amount>"

@Dolivent thoughts?

**Comment by Dolivent** [comment]
Sorry, Just saw this.

Yeah fine the way youve set it up. As long the user can see current vs initial position, should be fine
